version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tinnova-postgres
    environment:
      POSTGRES_DB: veiculos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tinnova-network

  redis:
    image: redis:7-alpine
    container_name: tinnova-redis
    ports:
      - "6379:6379"
    networks:
      - tinnova-network

volumes:
  postgres_data:

networks:
  tinnova-network:
    driver: bridge